[package]
name = "nostr-probe"
version = "0.1.0"
edition = "2021"
authors = ["Mike Dilger <mike@mikedilger.com>"]
description = "Command line tools for nostr"
keywords = [ "nostr" ]
license = "MIT"

[dependencies]
